theme: jekyll-theme-slate
author: "CutThroat78"
title: "toki pona Words & Phrases"
description: "Tables of words & phrases for learners learning the toki pona language"
show_downloads: false
github:
   is_project_page: false
